### ISSUE TITLE
Efficient cpp solution using dfs.

### ISSUE THREAD

**Issue by asv02** [Gupta-Nikhil85/LC-Google-Pr#13]

**Comment by asv02** [comment]
I want to add an efficient solution for different questions with explanations @Gupta-Nikhil85

**Comment by Gupta-Nikhil85** [comment]
@asv02 do read the readme file of the project.
The main purpose is to add questions from the link provided in readme file.
If your problem is listed in this [https://drive.google.com/file/d/1Jri_FTEXlJ8WqZpHvF8L7dhFY8XF_3JO/view](document), feel free to do add the solutions.
